#!/bin/zsh
# fp-docs shell prompt integration
# Generated by /fp-docs:setup
#
# Add to your .zshrc:
#   source "/Users/tom.kyser/FP LOCAL DEV/cc-plugins/fp-docs/plugins/fp-docs/framework/templates/fp-docs-prompt.zsh"

# Baked paths
_FP_CODEBASE_ROOT="/Users/tom.kyser/FP LOCAL DEV/foreignpolicy.com/wordpress/wp-content"
_FP_DOCS_ROOT="/Users/tom.kyser/FP LOCAL DEV/foreignpolicy.com/wordpress/wp-content/themes/foreign-policy-2017/docs"

# Returns docs branch sync status for prompt integration
fp_docs_status() {
  # Only run when inside the codebase directory
  [[ "$PWD" == "$_FP_CODEBASE_ROOT"* ]] || return

  if [[ ! -d "$_FP_DOCS_ROOT/.git" ]]; then
    echo " %F{red}[docs:missing]%f"
    return
  fi

  local cb=$(git -C "$_FP_CODEBASE_ROOT" branch --show-current 2>/dev/null)
  local db=$(git -C "$_FP_DOCS_ROOT" branch --show-current 2>/dev/null)

  if [[ -z "$cb" || -z "$db" ]]; then
    echo " %F{yellow}[docs:detached]%f"
  elif [[ "$cb" == "$db" ]]; then
    # Check for uncommitted docs changes
    local dirty=$(git -C "$_FP_DOCS_ROOT" status --porcelain 2>/dev/null | head -1)
    if [[ -n "$dirty" ]]; then
      echo " %F{yellow}[docs:$db*]%f"
    else
      echo " %F{green}[docs:$db]%f"
    fi
  else
    echo " %F{red}[docs:$db!=$cb]%f"
  fi
}

# Hook into precmd to update prompt
_fp_docs_precmd() {
  _FP_DOCS_PROMPT="$(fp_docs_status)"
}

# Register precmd hook (idempotent)
autoload -Uz add-zsh-hook
add-zsh-hook precmd _fp_docs_precmd

# Usage: append ${_FP_DOCS_PROMPT} to your PROMPT or RPROMPT
# Example: RPROMPT='${_FP_DOCS_PROMPT}'
